/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Componentes.Render;
import TechnicalFace.TechnicalFace;
import TechnicalFace.Tecnico;
import TechnicalFace.Usuario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author root
 */
public class BuscarTecnico extends javax.swing.JFrame {
    DefaultTableModel modeloTabla;
    TechnicalFace technical = new TechnicalFace();
    Usuario usu;
    Tecnico tec;
    public TableRowSorter trs;
    /**
     * Creates new form JFrameBuscarTecnico
     * @param usu es el  Usuario que quiere buscar un tecnico
     */
    public BuscarTecnico(Usuario usu) {
        this.usu = usu;
        initComponents();
        technical.setTecnicos(new ArrayList<>());
        technical.setUsuarios(new ArrayList<>());
        technical.cargarSistema();
        listarRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBusqueda);

        jLabel1.setText("Filtrar Por:");

        jRadioButton1.setText("Region");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });

        jRadioButton2.setText("Provincia");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });

        jRadioButton3.setText("Comuna");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Filtrar Por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Nombre", "Apellido Paterno", "Apellido Materno", "Especialidad"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("O por");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Buscar:");

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void jTextField5KeyTyped(java.awt.event.KeyEvent evt) { 
        switch (this.jComboBox1.getSelectedIndex()) {
            case 1:
                this.jTextField5.addKeyListener(new KeyAdapter(){
                    @Override
                    public void keyReleased(final KeyEvent evt){
                        trs.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField5.getText(),0));
                    }
                }); 
                trs = new TableRowSorter(modeloTabla);
                this.tablaBusqueda.setRowSorter(trs);
                break;
            case 2:
                this.jTextField5.addKeyListener(new KeyAdapter(){
                    @Override
                    public void keyReleased(final KeyEvent evt){
                        trs.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField5.getText(),1));
                    }
                });
                trs = new TableRowSorter(modeloTabla);
                this.tablaBusqueda.setRowSorter(trs);
                break;
            case 3:
                this.jTextField5.addKeyListener(new KeyAdapter(){
                    @Override
                    public void keyReleased(final KeyEvent evt){
                        trs.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField5.getText(),2));
                    }
                });
                trs = new TableRowSorter(modeloTabla);
                this.tablaBusqueda.setRowSorter(trs);
                break;
            case 4:
                this.tablaBusqueda.addKeyListener(new KeyAdapter(){
                    @Override
                    public void keyReleased(final KeyEvent evt){
                        trs.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField5.getText(),3));
                    }
                });
                trs = new TableRowSorter(modeloTabla);
                this.tablaBusqueda.setRowSorter(trs);
                break;
            default:
                break;
        }
        if(this.jRadioButton1.isSelected()){
            
            this.jTextField5.addKeyListener(new KeyAdapter(){
                    @Override
                    public void keyReleased(final KeyEvent evt){
                        trs.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField5.getText(),4));
                    }
                }); 
                trs = new TableRowSorter(modeloTabla);
                this.tablaBusqueda.setRowSorter(trs);
        }
        if (this.jRadioButton2.isSelected()) {
            
            this.jTextField5.addKeyListener(new KeyAdapter(){
                    @Override
                    public void keyReleased(final KeyEvent evt){
                        
                        trs.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField5.getText(),5));
                    }
                }); 
                trs = new TableRowSorter(modeloTabla);
                this.tablaBusqueda.setRowSorter(trs);
        }
        if (this.jRadioButton3.isSelected()) {
            
            this.jTextField5.addKeyListener(new KeyAdapter(){
                    @Override
                    public void keyReleased(final KeyEvent evt){
                        trs.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField5.getText(),6));
                    }
                }); 
                trs = new TableRowSorter(modeloTabla);
                this.tablaBusqueda.setRowSorter(trs);
        }
        
    } 
    
    private void tablaBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusquedaMouseClicked
        int column = tablaBusqueda.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tablaBusqueda.getRowHeight();
        
        if(row < tablaBusqueda.getRowCount() && row >= 0 && column < tablaBusqueda.getColumnCount() && column >= 0){
            Object value = tablaBusqueda.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                if(boton.getName().equals("Ver Perfil")){
                  value = tablaBusqueda.getValueAt(row, 0);
                  Object value2 = tablaBusqueda.getValueAt(row, 1);
                  Object value3 = tablaBusqueda.getValueAt(row, 2);
                  if (value instanceof String && value2 instanceof String && value3 instanceof String) {
                    String da0 = (String)value;
                    String da2 = (String)value2;
                    String da3 = (String)value3;
                    String da = da0+" "+da2+" "+da3;
                        for (int i = 0; i < technical.cantidadRegistroTecnico(); i++) {
                            tec = technical.obtenerRegistroTecnico(i);
                            String da1 =""+tec.getNombre()+" "+tec.getAp_paterno()+" "+tec.getAp_materno();
                            System.out.println(da1);
                            System.out.println(da);
                            if (da.equals(da1)) {
                                PerfilTecnico perfilTecnico = new PerfilTecnico(true,usu, tec);
                                perfilTecnico.setVisible(true);
                                dispose();   
                            }    
                        }

            }
                
               }
            }
//            
        }
    }//GEN-LAST:event_tablaBusquedaMouseClicked

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        if (this.jRadioButton1.isSelected()) {
            this.jRadioButton2.setSelected(false);
            this.jRadioButton3.setSelected(false);
            
        }
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        if (this.jRadioButton2.isSelected()) {
            this.jRadioButton1.setSelected(false);
            this.jRadioButton3.setSelected(false);
            
        }
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (this.jRadioButton3.isSelected()) {
            this.jRadioButton1.setSelected(false);
            this.jRadioButton2.setSelected(false);
            
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /*
    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyTyped
 */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        this.jRadioButton1.setSelected(false);
        this.jRadioButton2.setSelected(false);
        this.jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PerfilUsuario perfilUsuario = new PerfilUsuario(usu);
        perfilUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
  
     private void listarRegistro(){
        tablaBusqueda.setDefaultRenderer(Object.class, new Render());
        modeloTabla = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido Paterno");
        modeloTabla.addColumn("Apellido Materno");
        modeloTabla.addColumn("Especialidad");
        modeloTabla.addColumn("Region");
        modeloTabla.addColumn("Provincia");
        modeloTabla.addColumn("Comuna");
        modeloTabla.addColumn("");
        JButton verperfil = new JButton("Ver Perfil");
        verperfil.setName("Ver Perfil");
        Object fila[] = new Object[8];
        for(int i = 0; i < technical.cantidadRegistroTecnico(); i++){
            Tecnico tec = technical.obtenerRegistroTecnico(i);
            fila[0] = ""+tec.getNombre();
            fila[1] = tec.getAp_paterno();
            fila[2] = tec.getAp_materno();
            fila[3] =  tec.getEspecialidad();
            fila[4] = ""+tec.getDireccion().getRegion();
            fila[5] = ""+tec.getDireccion().getProvincia();
            fila[6] = ""+tec.getDireccion().getComuna();
            fila[7] = verperfil;
            modeloTabla.addRow(fila);
        }
        tablaBusqueda.setModel(modeloTabla);
        tablaBusqueda.setRowHeight(60);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tablaBusqueda;
    // End of variables declaration//GEN-END:variables
}
