/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Componentes.CargarComboBox;
import Componentes.EncryptionMD5;
import Componentes.GuardarImagenes;
import Componentes.Mensajes;
import Componentes.SeleccionarImagen;
import Componentes.validarCampos;
import TechnicalFace.Direccion;
import TechnicalFace.TechnicalFace;
import TechnicalFace.Tecnico;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
   
/**
 *
 * @author Gustavo Huerta
 */
public class EditarPerfilTecnico extends javax.swing.JFrame {
    TechnicalFace technical;
    Tecnico tec;
    int index= 0;
    /**
     * Creates new form ListaAmigosUsuario_1
     * @param tecnico
     */
    public EditarPerfilTecnico(Tecnico tecnico) {
        this.setTitle("Editar Perfil");
        initComponents();
        this.technical = new TechnicalFace();
        this.technical.setTecnicos(new ArrayList<>());
        technical.cargarSistema();
        CargarComboBox.cargar(cBoxRegion, "SELECT * FROM Regiones");
        this.txtNombres.setText(tecnico.getNombre());
        this.txtApPaterno.setText(tecnico.getAp_paterno());
        this.txtApMaterno.setText(tecnico.getAp_materno());
        this.txtCelular.setText(tecnico.getCelular());
        this.txtFonoFijo.setText(tecnico.getTelefono());
        this.txtCalle.setText(tecnico.getDireccion().getCalle());
        this.txtCorreo1.setText(tecnico.getCorreo());
        this.txtCorreo2.setText(tecnico.getCorreo());
        this.txtNumCalle.setText(tecnico.getDireccion().getNum_calle());
        this.txtUser.setText(tecnico.getUser());
        try {
            this.txtPass1.setText(EncryptionMD5.Desencriptar(tecnico.getPassword()));
            this.txtPass2.setText(EncryptionMD5.Desencriptar(tecnico.getPassword()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        this.ruta.setText(tecnico.getDirFotoPerfil());
        for (int i = 0; i < this.cBoxRegion.getItemCount(); i++) {
           this.cBoxRegion.setSelectedIndex(i);
           String c = this.cBoxRegion.getSelectedItem().toString();
           if (c.trim().equals(tecnico.getDireccion().getRegion().trim())) {
                break;
            }
        }
        for (int i = 0; i < this.cBoxProvincia.getItemCount(); i++) {
           this.cBoxProvincia.setSelectedIndex(i);
           String c = this.cBoxProvincia.getSelectedItem().toString();
           if (c.trim().equals(tecnico.getDireccion().getProvincia().trim())) {
                break;
            }
        }
        for (int i = 0; i < this.cBoxComuna.getItemCount(); i++) {
           this.cBoxComuna.setSelectedIndex(i);
           String c = this.cBoxComuna.getSelectedItem().toString();
           if (c.trim().equals(tecnico.getDireccion().getComuna().trim())) {
                break;
            }
        }
        for (int i = 0; i < this.jCBEspecialidad.getItemCount(); i++) {
           this.jCBEspecialidad.setSelectedIndex(i);
           String c = this.jCBEspecialidad.getSelectedItem().toString();
           if (c.trim().equals(tecnico.getEspecialidad().trim())) {
                break;
            }
        }
        for (int i = 0; i < this.jCBoxExp.getItemCount(); i++) {
           this.jCBoxExp.setSelectedIndex(i);
           String c = this.jCBoxExp.getSelectedItem().toString();
           if (c.trim().equals(tecnico.getAnoExperencia().trim())) {
                break;
            }
        }
        this.jTextArea1.setText(tecnico.getDescripcion());
        if (!tecnico.getDirFotoPerfil().equals("0")) {
            SeleccionarImagen.cargarImagen(tecnico.getDirFotoPerfil(), this.lblFoto);
        }
        index = technical.obtenerPosTecnico(tecnico);
        if (index == -1) {
            Mensajes.error("No se encuentra el tecnico a modificar");
        }
        this.tec = tecnico;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruta = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        panelGeneral = new javax.swing.JPanel();
        jCheckBoxDatos = new javax.swing.JCheckBox();
        panelPersonal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFonoFijo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCFono = new javax.swing.JComboBox<>();
        jPanelInPro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jCBEspecialidad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jCBoxExp = new javax.swing.JComboBox<>();
        jCheckBoxDir = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        cBoxRegion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cBoxProvincia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cBoxComuna = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        txtNumCalle = new javax.swing.JTextField();
        txtNDepar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        txtCorreo2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jCheckConfi = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jCheckBoxCorreo = new javax.swing.JCheckBox();
        jCheckBoxInfo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ruta.setVisible(false);
        ruta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                rutaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblFoto.setEnabled(false);
        lblFoto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFotoMouseMoved(evt);
            }
        });
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMouseClicked(evt);
            }
        });

        jCheckBoxDatos.setText("Configurar Datos Personales");
        jCheckBoxDatos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxDatosStateChanged(evt);
            }
        });

        panelPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        panelPersonal.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombres:");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombresKeyPressed(evt);
            }
        });

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });
        txtCelular.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Celular:");

        txtFonoFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFonoFijoKeyPressed(evt);
            }
        });
        txtFonoFijo.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefono fijo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");

        txtApPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApPaternoKeyPressed(evt);
            }
        });
        txtApPaterno.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");

        txtApMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApMaternoKeyPressed(evt);
            }
        });
        txtApMaterno.setEnabled(false);

        jLabel23.setText("+569");

        jCFono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+02", "+45", "+65", "+64" }));
        jCFono.setEnabled(false);

        javax.swing.GroupLayout panelPersonalLayout = new javax.swing.GroupLayout(panelPersonal);
        panelPersonal.setLayout(panelPersonalLayout);
        panelPersonalLayout.setHorizontalGroup(
            panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalLayout.createSequentialGroup()
                        .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(panelPersonalLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCFono, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        panelPersonalLayout.setVerticalGroup(
            panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(5, 5, 5)
                .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNombres.setEnabled(false);

        jPanelInPro.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Profesional"));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Especialidad:");

        jCBEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.." , "Informatica", "Gasfiter", "Enfermeria", "Metalicos", "Otra" }));
        jCBEspecialidad.setEnabled(false);

        jLabel11.setText("Comentario:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel24.setText("Años de Experencia:");

        jCBoxExp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 - 1 años", "1 - 2 años", "3 - 5 años", "mas de 5 años"}));
        jCBoxExp.setEnabled(false);

        javax.swing.GroupLayout jPanelInProLayout = new javax.swing.GroupLayout(jPanelInPro);
        jPanelInPro.setLayout(jPanelInProLayout);
        jPanelInProLayout.setHorizontalGroup(
            jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInProLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInProLayout.createSequentialGroup()
                        .addComponent(jCBEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel11))
                    .addComponent(jCBoxExp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelInProLayout.setVerticalGroup(
            jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInProLayout.createSequentialGroup()
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelInProLayout.createSequentialGroup()
                        .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCBEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBoxExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jCheckBoxDir.setText("Configurar Direccion");
        jCheckBoxDir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxDirStateChanged(evt);
            }
        });

        jPanel2.setEnabled(false);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion"));

        cBoxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cBoxRegion.setEnabled(false);
        cBoxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRegionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Región:");

        cBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        cBoxProvincia.setEnabled(false);
        cBoxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProvinciaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Provincia:");

        cBoxComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..."}));
        cBoxComuna.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Comuna:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Calle:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("N° de Calle:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("N° de Departamento:");

        txtCalle.setEnabled(false);

        txtNumCalle.setEnabled(false);

        txtNDepar.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(cBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo Electronico"));

        jLabel18.setText("Correo:");

        txtCorreo1.setEnabled(false);

        txtCorreo2.setEnabled(false);

        jLabel20.setText("Vuelve a ingresar correo:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jCheckConfi.setText("Configurar Perfil Usuario");
        jCheckConfi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckConfiStateChanged(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil Usuario"));
        jPanel4.setToolTipText("");

        jLabel15.setText("Nombre de Usuario:");

        txtUser.setEnabled(false);

        txtPass1.setEnabled(false);

        jLabel16.setText("Contraseña:");

        jLabel17.setText("ingresar contraseña:");

        txtPass2.setEnabled(false);

        jLabel25.setText("Vuelve a");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPass1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(txtUser))
                    .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );

        jCheckBoxCorreo.setText("Configurar Correo Electronico");
        jCheckBoxCorreo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxCorreoStateChanged(evt);
            }
        });
        jCheckBoxCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCorreoActionPerformed(evt);
            }
        });

        jCheckBoxInfo.setText("Configurar Información Personal");
        jCheckBoxInfo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxInfoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxDatos)
                    .addComponent(jCheckBoxDir)
                    .addComponent(jCheckBoxInfo)
                    .addComponent(jPanelInPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeneralLayout.createSequentialGroup()
                            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelGeneralLayout.createSequentialGroup()
                                    .addComponent(jCheckConfi)
                                    .addGap(177, 177, 177))
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxCorreo)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckConfi)
                    .addComponent(jCheckBoxCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jCheckBoxInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("Cambiar Foto Perfil");
        jCheckBox6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox6StateChanged(evt);
            }
        });

        jButton2.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jCheckBox6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGap(24, 24, 24)
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(jButton1)
                        .addGap(65, 65, 65)
                        .addComponent(jButton2))
                    .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseMoved
        this.lblFoto.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto Perfil"));
    }//GEN-LAST:event_lblFotoMouseMoved

    private void lblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseClicked
        if (this.jCheckBox6.isSelected()) {
            SeleccionarImagen.seleccionar(this.ruta, lblFoto);
        }
        
    }//GEN-LAST:event_lblFotoMouseClicked

    private void txtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyPressed
        validarCampos.cantCaracteres(txtNombres, 30);
        validarCampos.soloLetras(txtNombres);
    }//GEN-LAST:event_txtNombresKeyPressed

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        validarCampos.soloNumeros(txtCelular);
        validarCampos.cantCaracteres(txtCelular, 8);
    }//GEN-LAST:event_txtCelularKeyPressed

    private void txtFonoFijoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFonoFijoKeyPressed
        validarCampos.soloNumeros(txtFonoFijo);
        validarCampos.cantCaracteres(txtFonoFijo, 6);
    }//GEN-LAST:event_txtFonoFijoKeyPressed

    private void txtApPaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPaternoKeyPressed
        validarCampos.cantCaracteres(txtApPaterno, 20);
        validarCampos.soloLetras(txtApPaterno);
    }//GEN-LAST:event_txtApPaternoKeyPressed

    private void txtApMaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMaternoKeyPressed
        validarCampos.cantCaracteres(txtApMaterno, 20);
        validarCampos.soloLetras(txtApMaterno);
    }//GEN-LAST:event_txtApMaternoKeyPressed

    private void cBoxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRegionActionPerformed
        if (cBoxRegion.getSelectedIndex() > 0) {
            CargarComboBox.cargar(cBoxProvincia, "SELECT id_provincia, nom_provincia FROM Provincias INNER JOIN Regiones ON Provincias.id_region1 = Regiones.id_region WHERE id_region1 = " + (cBoxRegion.getSelectedIndex()) + "");
            cBoxComuna.removeAllItems();
            cBoxComuna.addItem("Seleccione...");

        }

    }//GEN-LAST:event_cBoxRegionActionPerformed

    private void cBoxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProvinciaActionPerformed
        if (cBoxProvincia.getSelectedIndex() > 0) {
            CargarComboBox.cargar(cBoxComuna, "SELECT id_comuna, nom_comuna FROM Comunas INNER JOIN Provincias ON Comunas.id_provincia1 = Provincias.id_provincia WHERE nom_provincia LIKE '" + cBoxProvincia.getSelectedItem().toString() + "'");
        }
    }//GEN-LAST:event_cBoxProvinciaActionPerformed

    private void jCheckBoxDatosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxDatosStateChanged
        boolean enabled = true;
        if (this.jCheckBoxDatos.isSelected()) {
            this.panelPersonal.setEnabled(enabled);
            this.txtNombres.setEnabled(enabled);
            this.txtApPaterno.setEnabled(enabled);
            this.txtApMaterno.setEnabled(enabled);
            this.txtCelular.setEnabled(enabled);
            this.txtFonoFijo.setEnabled(enabled);
            this.jCFono.setEnabled(enabled);
        }else if (!this.jCheckBoxDatos.isSelected()) {
            this.panelPersonal.setEnabled(!enabled);
            this.txtNombres.setEnabled(!enabled);
            this.txtApPaterno.setEnabled(!enabled);
            this.txtApMaterno.setEnabled(!enabled);
            this.txtCelular.setEnabled(!enabled);
            this.txtFonoFijo.setEnabled(!enabled);
            this.jCFono.setEnabled(!enabled);
        }
    }//GEN-LAST:event_jCheckBoxDatosStateChanged

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        
    }//GEN-LAST:event_txtNombresActionPerformed

    private void jCheckBox6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox6StateChanged
        if (this.jCheckBox6.isSelected()) {
            this.lblFoto.setEnabled(true);
        }else{
            this.lblFoto.setEnabled(false); 
        }
    }//GEN-LAST:event_jCheckBox6StateChanged

    private void jCheckBoxDirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxDirStateChanged
        boolean enabled = true;
        if (this.jCheckBoxDir.isSelected()) {
           this.jPanel2.setEnabled(enabled);
           this.cBoxRegion.setEnabled(enabled);
           this.cBoxProvincia.setEnabled(enabled);
           this.cBoxComuna.setEnabled(enabled);
           this.txtCalle.setEnabled(enabled);
           this.txtNumCalle.setEnabled(enabled);
           this.txtNDepar.setEnabled(enabled);
        }else{
            this.jPanel2.setEnabled(!enabled);
           this.cBoxRegion.setEnabled(!enabled);
           this.cBoxProvincia.setEnabled(!enabled);
           this.cBoxComuna.setEnabled(!enabled);
           this.txtCalle.setEnabled(!enabled);
           this.txtNumCalle.setEnabled(!enabled);
           this.txtNDepar.setEnabled(!enabled);
        }
    }//GEN-LAST:event_jCheckBoxDirStateChanged

    private void jCheckConfiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckConfiStateChanged
        boolean enabled = true;
        if (this.jCheckConfi.isSelected()) {
            this.jPanel4.setEnabled(enabled);
            this.txtUser.setEnabled(enabled);
            this.txtPass1.setEnabled(enabled);
            this.txtPass2.setEnabled(enabled);
        }else{
            this.jPanel4.setEnabled(!enabled);
            this.txtUser.setEnabled(!enabled);
            this.txtPass1.setEnabled(!enabled);
            this.txtPass2.setEnabled(!enabled);
        }
    }//GEN-LAST:event_jCheckConfiStateChanged

    private void jCheckBoxCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCorreoActionPerformed

    private void jCheckBoxCorreoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxCorreoStateChanged
        boolean enabled = true;
        if (this.jCheckBoxCorreo.isSelected()) {
            this.jPanel5.setEnabled(enabled);
            this.txtCorreo1.setEnabled(enabled);
            this.txtCorreo2.setEnabled(enabled);
        }else{
            this.jPanel5.setEnabled(!enabled);
            this.txtCorreo1.setEnabled(!enabled);
            this.txtCorreo2.setEnabled(!enabled);
        }
    }//GEN-LAST:event_jCheckBoxCorreoStateChanged

    private void jCheckBoxInfoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxInfoStateChanged
        boolean enabled = true;
        if (this.jCheckBoxInfo.isSelected()) {
            this.jPanelInPro.setEnabled(enabled);
            this.jCBEspecialidad.setEnabled(enabled);
            this.jCBoxExp.setEnabled(enabled);
            this.jTextArea1.setEnabled(enabled);
        }else{
            this.jPanelInPro.setEnabled(!enabled);
            this.jCBEspecialidad.setEnabled(!enabled);
            this.jCBoxExp.setEnabled(!enabled);
            this.jTextArea1.setEnabled(!enabled);
        }
    }//GEN-LAST:event_jCheckBoxInfoStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.jCheckBoxDatos.isSelected() || this.jCheckBoxDir.isSelected() ||
            this.jCheckConfi.isSelected() || this.jCheckBoxCorreo.isSelected() ||
            this.jCheckBoxInfo.isSelected() || this.jCheckBox6.isSelected()) {
            
            if (this.jCheckBoxDatos.isSelected()) {
                tec.setNombre(this.txtNombres.getText());
                tec.setAp_materno(this.txtApMaterno.getText());
                tec.setAp_paterno(this.txtApPaterno.getText());
                tec.setCelular(this.txtCelular.getText());
                tec.setTelefono(this.txtFonoFijo.getText());
            }
            if (this.jCheckBoxDir.isSelected()) {
                tec.setDireccion(new Direccion());
                tec.getDireccion().setRegion(this.cBoxRegion.getSelectedItem().toString());
                tec.getDireccion().setComuna(this.cBoxComuna.getSelectedItem().toString());
                tec.getDireccion().setProvincia(this.cBoxProvincia.getSelectedItem().toString());
                tec.getDireccion().setCalle(this.txtCalle.getText());
                tec.getDireccion().setNum_calle(this.txtNumCalle.getText());
                tec.getDireccion().setNum_dep(this.txtNDepar.getText());
            }
            if (this.jCheckConfi.isSelected()) {
                tec.setUser(this.txtUser.getText());
                tec.setPassword(EncryptionMD5.getStringMessageDigest(txtPass1.getText(),EncryptionMD5.MD5));
            }
            if (this.jCheckBoxCorreo.isSelected()) {
                tec.setCorreo(txtCorreo1.getText());
            }
            if (this.jCheckBoxInfo.isSelected()) {
                tec.setEspecialidad(this.jCBEspecialidad.getSelectedItem().toString());
                tec.setAnoExperencia(this.jCBoxExp.getSelectedItem().toString());
                tec.setDescripcion(this.jTextArea1.getText());
            }
            if (validarCamposObligatoriosTecnicos().equals("Ingrese los siguientes campos:\n")) {
                if ((validarContrasena() && this.jCheckConfi.isSelected()) || (this.jCheckBoxCorreo.isSelected()&& validarEmail())) {
                    if (validarCampos.validarFormtCorreo(txtCorreo1.getText())) {
                        if (this.jCheckBox6.isSelected()) {
                            if (!ruta.getText().equals(tec.getDirFotoPerfil())) {;
                                tec.setDirFotoPerfil(GuardarImagenes.saveImage(tec , ruta.getText()));
                            }else{
                                tec.setDirFotoPerfil("0");
                            }
                        }
                        technical.actualizarTecnico(index, tec);
                        technical.actualizar();
                        
                        Mensajes.informacion("Modificacion correcta");
                        Login login = new Login(tec);
                        login.setVisible(true);
                        dispose();
                    }else{
                        Mensajes.error("Error! En el formato del correo");
                    }    
     
                }else{
                    Mensajes.informacion("Las contraseñas o correos no son iguales");
                }
                
            }else{
                Mensajes.error(validarCamposObligatoriosTecnicos());
            }
        
            
        }else{
            Mensajes.informacion("Seleccione cualquier checkBox para modificar");
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rutaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rutaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaAncestorAdded
    public String validarCamposObligatoriosUsuario(){
        String informe = "Ingrese los siguientes campos:\n";
        if (this.jCheckBoxDatos.isSelected()) {
            if (this.txtNombres.getText().equals("")) {
                informe += "\tIngrese su Nombre\n";
            }
            if (this.txtApMaterno.getText().equals("")) {
                informe+= "\tIngrese su Apellido Materno\n";
            }
            if (this.txtApPaterno.getText().equals("")) {
                informe+= "\tIngrese su Apellido Paterno\n";
            }
        
        }
        if (this.jCheckBoxDir.isSelected()) {
            if (this.cBoxRegion.getSelectedIndex() == 0) {
                informe += "\tSelccione una Región\n";
            }
            if (this.cBoxProvincia.getSelectedIndex() == 0) {
                informe += "\tSeleccione una Cuidad\n";
            }
            if(this.cBoxComuna.getSelectedIndex() == 0){
                informe += "\tSeleccione una Comuna\n";
            }
            if (this.txtCalle.getText().equals("")) {
                informe += "\tIngrese la calle donde vives\n";
            }
            if (this.txtNumCalle.getText().equals("")) {
                informe += "\tIngrese el numero de la calle donde vive\n";
            }
        }
        if (this.jCheckConfi.isSelected()) {
            if (this.txtUser.getText().equals("")) {
            informe+= "\tIngrese su Nombre de Usuario\n";
            }
            String contrasena = new String(this.txtPass1.getPassword());
            if (contrasena.equals("")) {
                informe+= "\tIngrese su Contraseña\n";
            }
            String contrasena1 = new String(this.txtPass2.getPassword());
            if (contrasena1.equals("")) {
                informe+= "\tIngrese nuevamente la Contraseña\n";
            }
        }
        return informe;
    }
    public boolean validarContrasena(){
        boolean hola = true;
        if (this.jCheckConfi.isSelected()) {
            hola = validarCampos.validarPassword(this.txtPass1.getPassword(), this.txtPass2.getPassword());
        }
        return hola;
    }
    
    private boolean validarEmail() {
        boolean hola = true;
        if (this.jCheckBoxCorreo.isSelected()) {
            hola = validarCampos.validarCorreo(this.txtCorreo1.getText(),this.txtCorreo2.getText());
        }
        return hola;
    }
    public String validarCamposObligatoriosTecnicos(){
        String informe = validarCamposObligatoriosUsuario();
        if (this.jCheckBoxInfo.isSelected()) {
            if (this.jCBEspecialidad.getSelectedIndex() == 0) {
                informe += "\tSeleccione su especialidad\n";
            }
        }
        return informe;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cBoxComuna;
    private javax.swing.JComboBox<String> cBoxProvincia;
    private javax.swing.JComboBox<String> cBoxRegion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBEspecialidad;
    private javax.swing.JComboBox<String> jCBoxExp;
    private javax.swing.JComboBox<String> jCFono;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBoxCorreo;
    private javax.swing.JCheckBox jCheckBoxDatos;
    private javax.swing.JCheckBox jCheckBoxDir;
    private javax.swing.JCheckBox jCheckBoxInfo;
    private javax.swing.JCheckBox jCheckConfi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelInPro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel lblFoto;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelPersonal;
    private javax.swing.JLabel ruta;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtCorreo2;
    private javax.swing.JTextField txtFonoFijo;
    private javax.swing.JTextField txtNDepar;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumCalle;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
