/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
   

import Componentes.CargarComboBox;
import Componentes.EncryptionMD5;
import Componentes.GuardarImagenes;
import Componentes.Mensajes;
import Componentes.SeleccionarImagen;
import Componentes.validarCampos;
import TechnicalFace.Direccion;
import TechnicalFace.TechnicalFace;
import TechnicalFace.Tecnico;
import TechnicalFace.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
/**
 *
 * @author Gustavo Huerta
 */
public class RegistrarUsuario extends javax.swing.JFrame {
    
    TechnicalFace technicalFace;
    int cont = 0;

    /**
     * Creates new form RegistrarUsuario
     */

    public RegistrarUsuario(){
        this.setTitle("Registrar Usuario");
        this.technicalFace = new TechnicalFace();
        technicalFace.setTecnicos(new ArrayList<>());
        technicalFace.setUsuarios(new ArrayList<>());
        technicalFace.cargarSistema();
        initComponents();
        CargarComboBox.cargar(cBoxRegion, "SELECT * FROM Regiones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxRegistrar = new javax.swing.JComboBox<>();
        jButtonRegistrar = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFonoFijo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cBoxRegion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cBoxProvincia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cBoxComuna = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCalle = new javax.swing.JTextField();
        jTextFieldNCalle = new javax.swing.JTextField();
        jTextFieldNDepar = new javax.swing.JTextField();
        jPanelInPro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEsp = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        cBoxAnoExper = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNombreUser = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        txtCorreo2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        ruta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabel1.setText("Registrar como:");

        jComboBoxRegistrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Tecnico", "Usuario"}));
        jComboBoxRegistrar.setSelectedIndex(1);
        if(jComboBoxRegistrar.getSelectedIndex() == 1){
            this.jPanelInPro.setVisible(false);
        }
        jComboBoxRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRegistrarActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        lblFoto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFotoMouseMoved(evt);
            }
        });
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMouseClicked(evt);
            }
        });
        ImageIcon image = new ImageIcon("C:\\Users\\Gustavo Huerta\\Documents\\NetBeansProjects\\TechnicalFace\\src\\imagenesProyecto\\icono2.png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(235,318,Image.SCALE_DEFAULT ));
        lblFoto.setIcon(icon);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombres:");

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombresKeyPressed(evt);
            }
        });

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Celular:");

        txtFonoFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFonoFijoKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefono fijo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");

        txtApPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApPaternoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");

        txtApMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApMaternoKeyPressed(evt);
            }
        });

        jLabel23.setText("+569");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+02", "+45", "+65", "+64" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtFonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion"));

        cBoxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cBoxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRegionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Región:");

        cBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        cBoxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProvinciaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Provincia:");

        cBoxComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..."}));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Comuna:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Calle:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("N° de Calle:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("N° de Departamento:");

        jTextFieldCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCalleKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cBoxRegion, 0, 204, Short.MAX_VALUE)
                    .addComponent(jTextFieldCalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldNCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelInPro.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Profesional"));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Especialidad:");

        jComboBoxEsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatica", "Gasfiter", "Enfermeria", "Metalicos" }));

        jLabel11.setText("Comentario:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel24.setText("Años de Experencia:");

        cBoxAnoExper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 - 1 años", "1 - 2 años", "3 - 5 años", "mas de 5 años" }));

        javax.swing.GroupLayout jPanelInProLayout = new javax.swing.GroupLayout(jPanelInPro);
        jPanelInPro.setLayout(jPanelInProLayout);
        jPanelInProLayout.setHorizontalGroup(
            jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInProLayout.createSequentialGroup()
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cBoxAnoExper, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInProLayout.createSequentialGroup()
                        .addComponent(jComboBoxEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        jPanelInProLayout.setVerticalGroup(
            jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cBoxAnoExper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanelInProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil Usuario"));
        jPanel4.setToolTipText("");

        jLabel15.setText("Nombre de Usuario:");

        jLabel16.setText("Contraseña:");

        jLabel17.setText("ingresar contraseña:");

        jLabel25.setText("Vuelve a");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombreUser)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo Electronico"));

        jLabel18.setText("Correo:");

        jLabel20.setText("Vuelve a ingresar correo:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(txtCorreo2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Acepto Terminos & Condiciones");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel22MouseMoved(evt);
            }
        });

        ruta.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(ruta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelInPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBoxRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(389, 389, 389))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonRegistrar)
                        .addGap(471, 471, 471))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ruta)
                        .addGap(416, 416, 416))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelInPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRegistrar)
                        .addGap(0, 95, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(1069, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        try{
             if (this.jComboBoxRegistrar.getSelectedIndex() == 0) {
                this.ingresarTecnico();
            }else if (this.jComboBoxRegistrar.getSelectedIndex() == 1) {
                this.ingresarUsuario();
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed
    
    public void ingresarTecnico(){
        Tecnico tecnico = new Tecnico();
        if (this.jComboBoxRegistrar.getSelectedIndex() == 0) {
            tecnico.setId_persona(technicalFace.obtenerId_personaTecnico());
            tecnico.setNombre(this.txtNombres.getText());
            tecnico.setAp_materno(this.txtApMaterno.getText());
            tecnico.setAp_paterno(this.txtApPaterno.getText());
            tecnico.setCelular(this.txtCelular.getText());
            tecnico.setTelefono(this.txtFonoFijo.getText());
            tecnico.setUser(this.jTextFieldNombreUser.getText());
            tecnico.setPassword(EncryptionMD5.getStringMessageDigest(txtPassword1.getText(),EncryptionMD5.MD5));
            tecnico.setCorreo(txtCorreo1.getText());
            tecnico.setEspecialidad(this.jComboBoxEsp.getSelectedItem().toString());
            tecnico.setAnoExperencia(this.cBoxAnoExper.getSelectedItem().toString());
            tecnico.setDescripcion(this.jTextArea1.getText());
            tecnico.setDireccion(new Direccion());
            tecnico.setDirFotoPerfil(""+ruta.getText());
            tecnico.getDireccion().setRegion(this.cBoxRegion.getSelectedItem().toString());
            tecnico.getDireccion().setComuna(this.cBoxComuna.getSelectedItem().toString());
            tecnico.getDireccion().setProvincia(this.cBoxProvincia.getSelectedItem().toString());
            tecnico.getDireccion().setCalle(this.jTextFieldCalle.getText());
            tecnico.getDireccion().setNum_calle(this.jTextFieldNCalle.getText());
            tecnico.getDireccion().setNum_dep(this.jTextFieldNDepar.getText());
            if (validarCamposObligatoriosTecnicos().equals("Ingrese los siguientes campos:\n")) {
                if (validarContrasena() && validarEmail()) {
                    if (validarCampos.validarFormtCorreo(txtCorreo1.getText())) {
                        if (!ruta.getText().equals("")) {
                            tecnico.setDirFotoPerfil(GuardarImagenes.saveImage(ruta.getText()));
                        }else{
                            tecnico.setDirFotoPerfil("no tiene foto perfil");
                        }
                        technicalFace.guardarTecnico(tecnico);
                        
                        Mensajes.informacion("Felicidades se ha registrado");
                        Login login = new Login(tecnico);
                        login.setVisible(true);
                        dispose();
                    }else{
                        Mensajes.error("Error! En el formato del correo");
                    }    
     
                }else{
                    Mensajes.informacion("Las contraseñas o correos no son iguales");
                }
                
            }else{
                Mensajes.error(validarCamposObligatoriosTecnicos());
            }
        }
        
    }
    public void limpiar(){
        this.txtNombres.setText("");
        this.txtApPaterno.setText("");
        this.txtApMaterno.setText("");
        this.txtCelular.setText("");
        this.txtFonoFijo.setText("");
        this.txtCorreo1.setText("");
        this.txtCorreo2.setText("");
        this.txtPassword1.setText("");
        this.txtPassword2.setText("");
        this.cBoxRegion.setSelectedIndex(0);
        this.cBoxProvincia.setSelectedIndex(0);
        this.cBoxComuna.setSelectedIndex(0);
        this.jCheckBox1.setSelected(false);
        this.jComboBox1.setSelectedIndex(0);
        this.cBoxAnoExper.setSelectedIndex(0);
        this.jTextArea1.setText("");
    }
    public void ingresarUsuario(){
         Usuario usuario = new Usuario();
        if (this.jComboBoxRegistrar.getSelectedIndex() == 1) {
            usuario.setId_persona(technicalFace.obtenerId_personaUsuario());
            usuario.setNombre(this.txtNombres.getText());
            usuario.setAp_materno(this.txtApMaterno.getText());
            usuario.setAp_paterno(this.txtApPaterno.getText());
            usuario.setCelular(this.txtCelular.getText());
            usuario.setTelefono(this.txtFonoFijo.getText());
            usuario.setUser(this.jTextFieldNombreUser.getText());
            usuario.setPassword(EncryptionMD5.getStringMessageDigest(txtPassword1.getText(),EncryptionMD5.MD5));
            usuario.setCorreo(this.txtCorreo1.getText());
            usuario.setDireccion(new Direccion());
            usuario.getDireccion().setRegion(this.cBoxRegion.getSelectedItem().toString());
            usuario.getDireccion().setComuna(this.cBoxComuna.getSelectedItem().toString());
            usuario.getDireccion().setProvincia(this.cBoxProvincia.getSelectedItem().toString());
            usuario.getDireccion().setCalle(this.jTextFieldCalle.getText());
            usuario.getDireccion().setNum_calle(this.jTextFieldNCalle.getText());
            usuario.getDireccion().setNum_dep(this.jTextFieldNDepar.getText());
            if (validarCamposObligatoriosUsuario().equals("Ingrese los siguientes campos:\n")) {
                if (this.validarContrasena() && this.validarEmail()){
                    if (validarCampos.validarFormtCorreo(this.txtCorreo2.getText())) {
                        if (!ruta.getText().equals("")) {
                            usuario.setDirFotoPerfil(GuardarImagenes.saveImage(ruta.getText()));
                        }else{
                            usuario.setDirFotoPerfil("no tiene foto perfil");
                        }
                        technicalFace.guardarUsuario(usuario);
                    }else{ 
                        Mensajes.error("Error! En el formato del correo");
                    }
                }else{
                   Mensajes.informacion("Las contraseñas o correos no son iguales");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, validarCamposObligatoriosUsuario());
            }
        }
        
    }
    public String validarCamposObligatoriosUsuario(){
        String informe = "Ingrese los siguientes campos:\n";
        if (this.txtNombres.getText().equals("")) {
            informe += "\tIngrese su Nombre\n";
        }
        if (this.txtApMaterno.getText().equals("")) {
            informe+= "\tIngrese su Apellido Materno\n";
        }
        if (this.txtApPaterno.getText().equals("")) {
            informe+= "\tIngrese su Apellido Paterno\n";
        }
        if (this.cBoxRegion.getSelectedIndex() == 0) {
            informe += "\tSelccione una Región\n";
        }
        if (this.cBoxProvincia.getSelectedIndex() == 0) {
            informe += "\tSeleccione una Cuidad\n";
        }
        if(this.cBoxComuna.getSelectedIndex() == 0){
            informe += "\tSeleccione una Comuna\n";
        }
        if (this.jTextFieldCalle.getText().equals("")) {
            informe += "\tIngrese la calle donde vives\n";
        }
        if (this.jTextFieldNCalle.getText().equals("")) {
            informe += "\tIngrese el numero de la calle donde vive\n";
        }
        if (this.jTextFieldNombreUser.getText().equals("")) {
            informe+= "\tIngrese su Nombre de Usuario\n";
        }
        String contrasena = new String(this.txtPassword1.getPassword());
        if (contrasena.equals("")) {
            informe+= "\tIngrese su Contraseña\n";
        }
        String contrasena1 = new String(this.txtPassword2.getPassword());
        if (contrasena1.equals("")) {
            informe+= "\tIngrese nuevamente la Contraseña\n";
        }
        return informe;
    }
    public boolean validarContrasena(){
        return validarCampos.validarPassword(this.txtPassword1.getPassword(), this.txtPassword2.getPassword());
    }
    
    private boolean validarEmail() {
        return validarCampos.validarCorreo(this.txtCorreo1.getText(),this.txtCorreo2.getText());
    }
    public String validarCamposObligatoriosTecnicos(){
        String informe = validarCamposObligatoriosUsuario();
        if (this.jComboBoxEsp.getSelectedIndex() == 0) {
            informe += "\tSeleccione su especialidad\n";
        }
        return informe;
    }
    private void lblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseClicked
        
        SeleccionarImagen.selccionar(this.ruta, lblFoto);
    }//GEN-LAST:event_lblFotoMouseClicked

    private void jComboBoxRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRegistrarActionPerformed
        
        if (this.jComboBoxRegistrar.getSelectedItem().equals("Usuario")) {
            this.jPanelInPro.setVisible(false);
        }else if(this.jComboBoxRegistrar.getSelectedIndex() == 0){
            this.jPanelInPro.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxRegistrarActionPerformed

    private void jLabel22MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseMoved
        this.jLabel22.setForeground(Color.blue);
    }//GEN-LAST:event_jLabel22MouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        this.jLabel22.setForeground(Color.WHITE);
        this.lblFoto.setBorder(null);
    }//GEN-LAST:event_formMouseMoved

    private void lblFotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseMoved
     this.lblFoto.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto Perfil"));
    }//GEN-LAST:event_lblFotoMouseMoved

    private void txtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyPressed
        validarCampos.cantCaracteres(txtNombres, 30);
        validarCampos.soloLetras(txtNombres);
    }//GEN-LAST:event_txtNombresKeyPressed

    private void txtApPaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPaternoKeyPressed
        validarCampos.cantCaracteres(txtApPaterno, 20);
        validarCampos.soloLetras(txtApPaterno);
    }//GEN-LAST:event_txtApPaternoKeyPressed

    private void txtApMaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMaternoKeyPressed
        validarCampos.cantCaracteres(txtApMaterno, 20);
        validarCampos.soloLetras(txtApMaterno);
    }//GEN-LAST:event_txtApMaternoKeyPressed

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        validarCampos.soloNumeros(txtCelular);
        validarCampos.cantCaracteres(txtCelular, 8);
    }//GEN-LAST:event_txtCelularKeyPressed

    private void txtFonoFijoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFonoFijoKeyPressed
        validarCampos.soloNumeros(txtFonoFijo);
        validarCampos.cantCaracteres(txtFonoFijo, 6);
    }//GEN-LAST:event_txtFonoFijoKeyPressed

    private void cBoxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRegionActionPerformed
        if (cBoxRegion.getSelectedIndex() > 0) {
            CargarComboBox.cargar(cBoxProvincia, "SELECT id_provincia, nom_provincia FROM Provincias INNER JOIN Regiones ON Provincias.id_region1 = Regiones.id_region WHERE id_region1 = " + (cBoxRegion.getSelectedIndex()) + "");
            cBoxComuna.removeAllItems();
            cBoxComuna.addItem("Seleccione...");
         
        }
  
    }//GEN-LAST:event_cBoxRegionActionPerformed

    private void cBoxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProvinciaActionPerformed
        if (cBoxProvincia.getSelectedIndex() > 0) {
            CargarComboBox.cargar(cBoxComuna, "SELECT id_comuna, nom_comuna FROM Comunas INNER JOIN Provincias ON Comunas.id_provincia1 = Provincias.id_provincia WHERE nom_provincia LIKE '" + cBoxProvincia.getSelectedItem().toString() + "'");
        }
    }//GEN-LAST:event_cBoxProvinciaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextFieldCalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCalleKeyPressed
        validarCampos.cantCaracteres(jTextFieldCalle, 20);
        validarCampos.soloLetras(jTextFieldCalle);
    }//GEN-LAST:event_jTextFieldCalleKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println(ex.getMessage());
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cBoxAnoExper;
    private javax.swing.JComboBox<String> cBoxComuna;
    private javax.swing.JComboBox<String> cBoxProvincia;
    private javax.swing.JComboBox<String> cBoxRegion;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxEsp;
    private javax.swing.JComboBox<String> jComboBoxRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelInPro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldNCalle;
    private javax.swing.JTextField jTextFieldNDepar;
    private javax.swing.JTextField jTextFieldNombreUser;
    public javax.swing.JLabel lblFoto;
    private javax.swing.JLabel ruta;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtCorreo2;
    private javax.swing.JTextField txtFonoFijo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    // End of variables declaration//GEN-END:variables

}
